from langchain_community.document_loaders import AsyncChromiumLoader
from langchain_community.document_transformers import Html2TextTransformer
import json

urlss = [
       "https://www.vultr.com/products/cloud-compute/"
    #   "https://scaledagile.com/training/safe-release-train-engineer/",
    #   "https://scaledagile.com/partner-finder/partners/?capabilities=SAFe%20Client%20Services%20Delivery",
    #   "https://scaledagile.com/business-solutions/safe-enterprise/",
    #   "https://scaledagile.com/safe-certification/",
    #   "https://scaledagile.com/training/implementing-safe/",
    #   "https://community.scaledagile.com/s/newmembership?language=en_US&_ga=2.15126070.1040316966.1701463348-844052646.1699999539",
    #   "https://scaledagile.com/training/safe-devops/",
    #   "https://scaledagile.com/training/agile-software-engineering/"
    # "https://docs.ozonetel.com/docs/ivr-hangup-details-report-1",
    # "https://docs.ozonetel.com/docs/cloudagent-22",
    # "https://docs.ozonetel.com/docs/status-filter",
    # "https://docs.ozonetel.com/docs/cloud-agent-integration-with-zoho",
    # "https://docs.ozonetel.com/docs/overview-1",
    # "https://docs.ozonetel.com/docs/campaign-type-filter",
    # "https://docs.ozonetel.com/docs/what-is-the-process-to-activate-dnd-do-not-disturb-calling-for-a-campaign",
    # "https://docs.ozonetel.com/docs/performance-analytics-report",
    # "https://docs.ozonetel.com/docs/is-it-mandatory-to-prefix-the-phone-number-with-0",
    # "https://docs.ozonetel.com/docs/agent-productivity-report",
    # "https://docs.ozonetel.com/docs/inbound-campaigns",
    # "https://docs.ozonetel.com/docs/quick-start-guide",
    # "https://docs.ozonetel.com/docs/threshold",
    # "https://docs.ozonetel.com/docs/organization-metrics-report",
    # "https://docs.ozonetel.com/docs/introduction-to-new-dashboards",
    # "https://docs.ozonetel.com/docs/what-part-of-the-conversation-does-call-recording-include",
    # "https://docs.ozonetel.com/docs/filters",
    # "https://docs.ozonetel.com/docs/handling-chat-digital-channels",
    # "https://docs.ozonetel.com/docs/india-south",
    # "https://docs.ozonetel.com/docs/how-to-generate-a-report",
    # "https://docs.ozonetel.com/docs/outbound-whatsapp-report",
    # "https://docs.ozonetel.com/docs/agent-is-not-receiving-any-callsoffline-or-online",
    # "https://docs.ozonetel.com/docs/understanding-agent-interface",
    # "https://docs.ozonetel.com/docs/campaign-productivity-report",
    # "https://docs.ozonetel.com/docs/conference-details-report-1",
    # "https://docs.ozonetel.com/docs/manage-numbers",
    # "https://docs.ozonetel.com/docs/hourly-calls-analysis-report",
    # "https://docs.ozonetel.com/docs/performance-report",
    # "https://docs.ozonetel.com/docs/agent-settings",
    # "https://docs.ozonetel.com/docs/transferred-calls-report",
    # "https://docs.ozonetel.com/docs/phone-productivity-report",
    # "https://docs.ozonetel.com/docs/disposition-summary-report",
    # "https://docs.ozonetel.com/docs/sms-report",
    # "https://docs.ozonetel.com/docs/pri-utilization-report",
    # "https://docs.ozonetel.com/docs/outbound-call-summary-report",
    # "https://docs.ozonetel.com/docs/restore-a-campaign",
    # "https://docs.ozonetel.com/docs/digital-reports",
    # "https://docs.ozonetel.com/docs/digital-detail-report",
    # "https://docs.ozonetel.com/docs/queue-management-1",
    # "https://docs.ozonetel.com/docs/overview-2",
    # "https://docs.ozonetel.com/docs/marketing-campaign",
    # "https://docs.ozonetel.com/docs/hourly-call-details-report",
    # "https://docs.ozonetel.com/docs/hourly-agent-summary-report",
    # "https://docs.ozonetel.com/docs/agents",
    # "https://docs.ozonetel.com/docs/call-analytics",
    # "https://docs.ozonetel.com/docs/agent-call-summary-report",
    # "https://docs.ozonetel.com/docs/rules-management-1",
    # "https://docs.ozonetel.com/docs/skill-productivity-report",
    # "https://docs.ozonetel.com/docs/cloudagent-21",
    # "https://docs.ozonetel.com/docs/india-west",
    # "https://docs.ozonetel.com/docs/broadcast",
    # "https://docs.ozonetel.com/docs/logout-1",
    # "https://docs.ozonetel.com/docs/cloudagent-20",
    # "https://docs.ozonetel.com/docs/routing-logic-ivr",
    # "https://docs.ozonetel.com/docs/disposition-filter",
    # "https://docs.ozonetel.com/docs/outbound-digital-1",
    # "https://docs.ozonetel.com/docs/pause-reasons",
    # "https://docs.ozonetel.com/docs/whatsapp-configuration",
    # "https://docs.ozonetel.com/docs/disposition-summary-report-1",
    # "https://docs.ozonetel.com/docs/agents-reports",
    # "https://docs.ozonetel.com/docs/day-call-summary-report",
    # "https://docs.ozonetel.com/docs/customer-support-escalation-matrix",
    # "https://docs.ozonetel.com/docs/how-to-generate-reports",
    # "https://docs.ozonetel.com/docs/advanced-retries",
    # "https://docs.ozonetel.com/docs/agent-efficiency-report",
    # "https://docs.ozonetel.com/reference",
    # "https://docs.ozonetel.com/docs/holidays",
    # "https://docs.ozonetel.com/docs/cloudagent-24",
    # "https://docs.ozonetel.com/docs/dashboard",
    # "https://docs.ozonetel.com/docs/ivr-flows",
    # "https://docs.ozonetel.com/docs/outbound-campaigns",
    # "https://docs.ozonetel.com/docs/sla-report-1",
    # "https://docs.ozonetel.com/docs/campaigns",
    # "https://docs.ozonetel.com/docs/organization-summary-report",
    # "https://docs.ozonetel.com/docs/what-is-the-limit-for-outbound-ivr-call-blast",
    # "https://docs.ozonetel.com/docs/introduction",
    # "https://docs.ozonetel.com/docs/skill-filter",
    # "https://docs.ozonetel.com/docs/what-are-dispositions-and-its-uses",
    # "https://docs.ozonetel.com/docs/agent-performance-report",
    # "https://docs.ozonetel.com/docs/installation-of-cloud-agent-app-from-salesforce-appexchange",
    # "https://docs.ozonetel.com/edit/queue-management-1",
    # "https://docs.ozonetel.com/docs/crm-integrations",
    # "https://docs.ozonetel.com/docs/callback-url-configuration",
    # "https://docs.ozonetel.com/discuss",
    # "https://docs.ozonetel.com/docs/introduction-to-ivr-designer",
    # "https://docs.ozonetel.com/docs/logging-in",
    # "https://docs.ozonetel.com/docs/customer-hold-details-report",
    # "https://docs.ozonetel.com/docs/agent-overview",
    # "https://docs.ozonetel.com/docs/screen-pop-url",
    # "https://docs.ozonetel.com/docs/dashboard-1",
    # "https://docs.ozonetel.com/docs/agent-dispositions-report",
    # "https://docs.ozonetel.com/docs/dispositions-1",
    # "https://docs.ozonetel.com/docs/outbound-sms-whatsapp",
    # "https://docs.ozonetel.com/docs/what-is-meant-by-acw-for-unanswered-calls",
    # "https://docs.ozonetel.com/docs/historic-reports",
    # "https://docs.ozonetel.com/docs/skills",
    # "https://docs.ozonetel.com/docs/location-filter",
    # "https://docs.ozonetel.com/docs/outbound-campaign-functions",
    # "https://docs.ozonetel.com/docs/rules-management",
    # "https://docs.ozonetel.com/docs/integration-with-hubspot",
    # "https://docs.ozonetel.com/docs/what-is-transfer-number-feature-whose-number-it-captures-and-its-use-case",
    # "https://docs.ozonetel.com/docs/agent-login-report",
    # "https://docs.ozonetel.com/docs/ivr-hangup-details-report",
    # "https://docs.ozonetel.com/docs/whatsapp-switch-board-in-cloudagent",
    # "https://docs.ozonetel.com/docs/call-type-filter",
    # "https://docs.ozonetel.com/docs/locations",
    # "https://docs.ozonetel.com/docs/sla-report",
    # "https://docs.ozonetel.com/docs/daily-call-summary-report",
    # "https://docs.ozonetel.com/docs/how-can-we-change-the-admin-password",
    # "https://docs.ozonetel.com/docs/hourly-phone-call-report",
    # "https://docs.ozonetel.com/docs/nodes-and-its-features",
    # "https://docs.ozonetel.com/docs/using-apis-in-ivr-designer",
    # "https://docs.ozonetel.com/docs/cloudagent-30",
    # "https://docs.ozonetel.com/docs/calls-are-overlapping-or-braking-or-cracking",
    # "https://docs.ozonetel.com/docs/admin-settings",
    # "https://docs.ozonetel.com/docs/phone-name-filter",
    # "https://docs.ozonetel.com/docs/port-utilisation-report",
    # "https://docs.ozonetel.com/docs/outbound-voice-1",
    # "https://docs.ozonetel.com/docs/scheduler",
    # "https://docs.ozonetel.com/docs/groups",
    # "https://docs.ozonetel.com/docs/india-north",
    # "https://docs.ozonetel.com/docs/missed-call-reports",
    # "https://docs.ozonetel.com/docs/chat-callback-format",
    # "https://docs.ozonetel.com/docs/templates",
    # "https://docs.ozonetel.com/docs/what-is-the-process-for-adding-pause-breaks-for-an-agent",
    # "https://docs.ozonetel.com/docs/what-is-the-use-of-the-campaign-priority-feature",
    # "https://docs.ozonetel.com/docs/building-a-dashboard",
    # "https://docs.ozonetel.com/docs/dynamic-did",
    # "https://docs.ozonetel.com/docs/international",
    # "https://docs.ozonetel.com/docs/agent-break-details-report",
    # "https://docs.ozonetel.com/docs/reports",
    # "https://docs.ozonetel.com/docs/transferred-filter",
    # "https://docs.ozonetel.com/docs/cloud-agent-integration-with-freshdesk",
    # "https://docs.ozonetel.com/docs/dialer-management",
    # "https://docs.ozonetel.com/docs/digital-channels-details",
    # "https://docs.ozonetel.com/docs/offline-phone-overview",
    # "https://docs.ozonetel.com/docs/hourly-active-agents-report",
    # "https://docs.ozonetel.com/docs/inbound-call-analytics-report",
    # "https://docs.ozonetel.com/docs/rules-management-2",
    # "https://docs.ozonetel.com/docs/cloud-agent-integration-with-freshsales",
    # "https://docs.ozonetel.com/docs/skill-report",
    # "https://docs.ozonetel.com/docs/queue-management-2",
    # "https://docs.ozonetel.com/docs/port-utilization-report",
    # "https://docs.ozonetel.com/docs/queue-overview-report",
    # "https://docs.ozonetel.com/docs/ivr-feedback-report",
    # "https://docs.ozonetel.com/docs/dialer-count-details",
    # "https://docs.ozonetel.com/docs/bot-designer",
    # "https://docs.ozonetel.com/docs",
    # "https://docs.ozonetel.com/docs/call-cannot-be-placed-in-conference",
    # "https://docs.ozonetel.com/docs/sub-admin",
    # "https://docs.ozonetel.com/docs/predictive-campaign-performance-report",
    # "https://docs.ozonetel.com/docs/handling-whatsapp-chat-while-on-call",
    # "https://docs.ozonetel.com/docs/chat-routing-icr",
    # "https://docs.ozonetel.com/docs/mode-type-filter",
    # "https://docs.ozonetel.com/docs/agent-state-details-report",
    # "https://docs.ozonetel.com/docs/call-forwarding-from-tfn-or-moblie",
    # "https://docs.ozonetel.com/docs/cloud-agent-integration-with-zendesk",
    # "https://docs.ozonetel.com/docs/other-features",
    # "https://docs.ozonetel.com/docs/organization-overview-report",
    # "https://docs.ozonetel.com/docs/call-details-report",
    # "https://docs.ozonetel.com/docs/call-detail-reports",
    # "https://docs.ozonetel.com/docs/conference-details-report",
    # "https://docs.ozonetel.com/docs/what-load-capacity-can-ozonetel-handle",
    # "https://docs.ozonetel.com/docs/customer-hold-reports",
    # "https://docs.ozonetel.com/docs/agent-filter",
    # "https://docs.ozonetel.com/docs/customer-interaction-details-report",
    # "https://docs.ozonetel.com/docs/duration-filter",
    # "https://docs.ozonetel.com/docs/can-we-add-the-office-landline-number-to-the-phone-numbers",
    # "https://docs.ozonetel.com/docs/predictive-campaign-performance",
    # "https://docs.ozonetel.com/docs/chat-disposition-summary-report",
    # "https://docs.ozonetel.com/docs/custom-reports",
    # "https://docs.ozonetel.com/docs/ivr-feedback-details-report",
    # "https://docs.ozonetel.com/docs/cloudagent-25",
    # "https://docs.ozonetel.com/docs/call-event-filter",
    # "https://docs.ozonetel.com/docs/campaign-filter",
    # "https://docs.ozonetel.com/docs/getting-started",
    # "https://docs.ozonetel.com/docs/quick-start-series",
    # "https://docs.ozonetel.com/docs/missed-call-details-report",
    # "https://docs.ozonetel.com/docs/queue-management",
    # "https://docs.ozonetel.com/docs/voice-mail-report",
    # "https://docs.ozonetel.com/docs/inbound-call-summary",
    # "https://docs.ozonetel.com/docs/agent-summary-report",
    # "https://docs.ozonetel.com/docs/calls-are-getting-disconnected-automatically-in-queue",
    # "https://docs.ozonetel.com/docs/what-is-the-difference-between-full-conversation-recording-and-their-use-cases",
    # "https://docs.ozonetel.com/docs/mappings",
    # "https://docs.ozonetel.com/docs/home-dashboard",
    # "https://docs.ozonetel.com/docs/audit-log-report",
    # "https://docs.ozonetel.com/docs/hourly-agent-call-report",
    # "https://docs.ozonetel.com/docs/callback-url-config",
    # "https://docs.ozonetel.com/docs/handling-voice-calls",
    # "https://docs.ozonetel.com/docs/glossary",
    # "https://docs.ozonetel.com/docs/agent-break-details",
    # "https://docs.ozonetel.com/docs/sip-locations",
    # "https://docs.ozonetel.com/",
    # "https://docs.ozonetel.com/docs/ivr-campaign",
    # "https://docs.ozonetel.com/docs/objective",
    # "https://docs.ozonetel.com/docs/what-information-is-required-to-implement-sso-integration-with-cloudagent",
    # "https://docs.ozonetel.com/docs/agent-login-details-report",
    # "https://docs.ozonetel.com/docs/unable-to-connect-to-a-did",
    # "https://docs.ozonetel.com/docs/call-backs-report",
    # "https://docs.ozonetel.com/docs/appendix",
    # "https://docs.ozonetel.com/docs/cloud-agent-integration-with-leadsquared",
    # "https://docs.ozonetel.com/docs/overview-3",
    # "https://docs.ozonetel.com/docs/dynamic-reports"
    ]


print(len(urlss))

output_file_path = "data.json"
all_data = []

for url in urlss:
    loader = AsyncChromiumLoader(urls=[url], headless=True, user_agent="USER_AGENT':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" )
    
    html = loader.load() 

    html2text = Html2TextTransformer()
    docs_transformed = html2text.transform_documents(html)
    content = docs_transformed[0].page_content[0: ]
    md = docs_transformed[0].metadata
    print(url)

    all_data.append({"page_content": content, "url": md})

with open(output_file_path, 'w', encoding='utf-8') as f:
    json.dump(all_data, f, indent=4, ensure_ascii=False)



    